version: "3"

services:
  ui:
    container_name: vue
    build: .
    volumes:
      - ./:/usr/app/
    ports:
      - 8080:8080
      - 8081:8081
    tty: true
    environment:
      - NODE_ENV=development